sed -i 's#Genesis #1+#g' BIB_CRONO
sed -i 's#Exodus #2+#g' BIB_CRONO
sed -i 's#Leviticus #3+#g' BIB_CRONO
sed -i 's#Numbers #4+#g' BIB_CRONO
sed -i 's#Deuteronomy #5+#g' BIB_CRONO
sed -i 's#Joshua #6+#g' BIB_CRONO
sed -i 's#Judges #7+#g' BIB_CRONO
sed -i 's#Ruth #8+#g' BIB_CRONO
sed -i 's#II_Samuel #10+#g' BIB_CRONO
sed -i 's#I_Samuel #9+#g' BIB_CRONO
sed -i 's#II_Kings #12+#g' BIB_CRONO
sed -i 's#I_Kings #11+#g' BIB_CRONO
sed -i 's#II_Chronicles #14+#g' BIB_CRONO
sed -i 's#I_Chronicles #13+#g' BIB_CRONO
sed -i 's#Ezra #15+#g' BIB_CRONO
sed -i 's#Nehemiah #16+#g' BIB_CRONO
sed -i 's#Esther #17+#g' BIB_CRONO
sed -i 's#Job #18+#g' BIB_CRONO
sed -i 's#Psalm #19+#g' BIB_CRONO
sed -i 's#Proverbs #20+#g' BIB_CRONO
sed -i 's#Ecclesiastes #21+#g' BIB_CRONO
sed -i 's#Song #22+#g' BIB_CRONO
sed -i 's#Isaiah #23+#g' BIB_CRONO
sed -i 's#Jeremiah #24+#g' BIB_CRONO
sed -i 's#Lamentations #25+#g' BIB_CRONO
sed -i 's#Ezekiel #26+#g' BIB_CRONO
sed -i 's#Daniel #27+#g' BIB_CRONO
sed -i 's#Hosea #28+#g' BIB_CRONO
sed -i 's#Joel #29+#g' BIB_CRONO
sed -i 's#Amos #30+#g' BIB_CRONO
sed -i 's#Obadiah #31+#g' BIB_CRONO
sed -i 's#Jonah #32+#g' BIB_CRONO
sed -i 's#Micah #33+#g' BIB_CRONO
sed -i 's#Nahum #34+#g' BIB_CRONO
sed -i 's#Habakkuk #35+#g' BIB_CRONO
sed -i 's#Zephaniah #36+#g' BIB_CRONO
sed -i 's#Haggai #37+#g' BIB_CRONO
sed -i 's#Zechariah #38+#g' BIB_CRONO
sed -i 's#Malachi #39+#g' BIB_CRONO
sed -i 's#Matthew #40+#g' BIB_CRONO
sed -i 's#Mark #41+#g' BIB_CRONO
sed -i 's#Luke #42+#g' BIB_CRONO
sed -i 's#Acts #44+#g' BIB_CRONO
sed -i 's#Romans #45+#g' BIB_CRONO
sed -i 's#II_Corinthians #47+#g' BIB_CRONO
sed -i 's#I_Corinthians #46+#g' BIB_CRONO
sed -i 's#Galatians #48+#g' BIB_CRONO
sed -i 's#Ephesians #49+#g' BIB_CRONO
sed -i 's#Philippians #50+#g' BIB_CRONO
sed -i 's#Colossians #51+#g' BIB_CRONO
sed -i 's#II_Thessalonians #53+#g' BIB_CRONO
sed -i 's#I_Thessalonians #52+#g' BIB_CRONO
sed -i 's#II_Timothy #55+#g' BIB_CRONO
sed -i 's#I_Timothy #54+#g' BIB_CRONO
sed -i 's#Titus #56+#g' BIB_CRONO
sed -i 's#Philemon #57+#g' BIB_CRONO
sed -i 's#Hebrews #58+#g' BIB_CRONO
sed -i 's#James #59+#g' BIB_CRONO
sed -i 's#II_Peter #61+#g' BIB_CRONO
sed -i 's#I_Peter #60+#g' BIB_CRONO
sed -i 's#III_John #64+#g' BIB_CRONO
sed -i 's#II_John #63+#g' BIB_CRONO
sed -i 's#I_John #62+#g' BIB_CRONO
sed -i 's#John #43+#g' BIB_CRONO
sed -i 's#Jude #65+#g' BIB_CRONO
sed -i 's#Revelation #66+#g' BIB_CRONO
